### ISSUE TITLE
Error while importing users

### ISSUE THREAD

**Issue by BenBo17** [t-markmann/nc-userimporter#43]
Hello. After I press "enter" to confirm the importing i receive the following error message:

```
When you are sure that your settings in the config.xml are correct,
press [ANY KEY] to continue.
Otherwise, press [CONTROL + C] to abort the process.

They have decided to continue. A user import preview is generated.

Traceback (most recent call last):
  File "nc-userimporter.py", line 328, in <module>
  File "c:\users\tm\appdata\local\programs\python\python37\lib\codecs.py", line 714, in __next__
  File "c:\users\tm\appdata\local\programs\python\python37\lib\codecs.py", line 645, in __next__
  File "c:\users\tm\appdata\local\programs\python\python37\lib\codecs.py", line 558, in readline
  File "c:\users\tm\appdata\local\programs\python\python37\lib\codecs.py", line 504, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 0: invalid continuation byte
[7392] Failed to execute script nc-userimporter
```

There are no ö,ä or ü in the user list.
I also noticed that the file path in the error message doesn't match with my windows user name. 
In february i ran the script for another nextcloud instance and it worked perfectly fine. So it can't be a dependency problem.

Ben

**Comment by BenBo17** [comment]
Solved it :D 
There was a "ß" in the user list
